/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_com_seetaface4android_H
#define _Included_com_seetaface4android_H
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_yanyu_com_seetaface4android_MRSeetaFaceUtil_seetaFaceDetectFaces
(JNIEnv *env, jclass obj,jlong, jlong );
#ifdef __cplusplus
}
#endif
#endif
